<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <Title>NLog.Targets.Http</Title>
    <Description>An NLog target for Http log entries submission (works wih Splunk HEC)</Description>
    <Authors>Dariusz Danielewski, Stan Smith and Julian Verdurmen</Authors>
    <CurrentYear>$([System.DateTime]::Now.ToString(yyyy))</CurrentYear>
    <Copyright>Copyright (c) 2020 Dariusz Danielewski, Stan Smith and Julian Verdurmen, Copyright 2013-2020 Splunk, Inc.</Copyright>
    <PackageTags>nlog;nlog-target;splunk;logging</PackageTags>
    <PackageIconUrl>https://raw.githubusercontent.com/DarekDan/NLog.Targets.HTTP/master/nlog.ico</PackageIconUrl>
    <PackageProjectUrl>https://github.com/DarekDan/NLog.Targets.HTTP</PackageProjectUrl>
    <PackageLicenseUrl></PackageLicenseUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>git://github.com/DarekDan/NLog.Targets.HTTP</RepositoryUrl>
    <Version>1.0.2</Version>
	  <Nullable>enable</Nullable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <!--common NuGet package refs -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>